# —————————
# 基础设置
mixed-port: 7890
redir-port: 7891
tproxy-port: 1536
ipv6: false
mode: Rule
allow-lan: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  ASN.mmdb: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
unified-delay: true
tcp-concurrent: true
log-level: silent
find-process-mode: always
global-client-fingerprint: chrome
external-controller: 0.0.0.0:9090
#面板默认 Meta 可选 Yacd / Zash 重启模块即可加载
external-ui: /data/adb/box_bll/panel/Zash/ # 主推zash
secret: ""
# —————————
# ==== Tips

# 1. 修改配置文件保存时，建议重启服务/重载配置.
# 2. 如遇 Web.apk 请求资源失败正在加载本地面板，或者代理组的图标无法显示，确保Tun保持开启状态下，您可先尝试 关闭/开启网络，亦或者检查是否能访问上 raw.githubusercontent.com
# —————————


# 健康检查
p: &p
  type: http
  interval: 86400
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 300
  header:
      User-Agent:
      - "mihomo/1.19.3"
      - "clash.meta"
# —————————

# 订阅地址相关
A: &A
  filter: "^(?!.*(套餐|重置|剩余|到期|订阅|群|账户|流量|有效期|时间|官网|失联|余额)).*$"
  use:
  - 1.主要地址
  - 2.备用地址
  - 3.额外地址

All: &All
  type: url-test
  use:
  - 1.主要地址
  - 2.备用地址
  - 3.额外地址

proxy-providers: # ← 此函数位置请勿变动！此为模块更新时备份恢复订阅变量范围 ↓
  1.主要地址:
    <<: *p
    override:
      additional-prefix: "五毛："
    path: ./proxies/1.主要地址.yaml
    url: "http://124.71.40.178/api/v1/client/subscribe?token=3b640536182e0936826f3a6bfab6f2a6"

  2.备用地址:
    <<: *p
    override:
      additional-prefix: "赔钱："
    path: ./proxies/2.备用地址.yaml
    url: "https://dash.pqjc.site/api/v1/client/subscribe?token=a334b2b75a2752222bf0f60eead1ee87"

  3.额外地址:
    <<: *p
    override:
      additional-prefix: "免费："
    path: ./proxies/3.额外地址.yaml
    url: "https://flynb.site/sub?token=oLKUUBC7cJPmouRzlnw2bg&tag=clash"

# —————————

# 节点记忆
profile: # ← 此函数位置请勿变动！此为模块更新时备份恢复订阅变量范围 ↑
  store-selected: true
  store-fake-ip: true
# —————————

# 嗅探模块
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "Mijia Cloud"
# —————————

# 网卡模块
tun:
  enable: true #true 开 #false 关 # 防止地址泄露此项必须开启
  device: meta
  stack: gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  udp-timeout: 300
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true
  route-exclude-address:
  - 192.168.0.0/16
  - fc00::/7
  exclude-package: # 游戏卡顿可添加包名 仅Android
    #- com.tencent.tmgp.sgame
    # _____________________# 三星专供 ↓ 范围
#    - com.samsung.android.messaging
#    - com.samsung.android.app.telephonyui
#    - com.samsung.android.dialer
#    - com.samsung.android.incallui
#    - com.samsung.android.smartcallprovider
#    - com.samsung.android.intellivoiceservice
#    - com.android.settings
#    - com.qti.qcc
#    - com.sec.epdg
#    - com.sec.imsservice # 三星专供 ↑ 范围
    # 如果你不是不必理会
    
# —————————

# DNS模块
# 解析不懂别瞎改养蛊 已最优解，你再怎么折腾也是没啥卵用
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "connect.rom.miui.com"
    - "localhost.ptlogin2.qq.com"
    - "+.market.xiaomi.com"
  direct-nameserver:
    - https://doh.pub/dns-query#🌎 全球直连
    - https://dns.alidns.com/dns-query#🌎 全球直连&h3=true
  proxy-server-nameserver:
    - https://doh.pub/dns-query#🌎 全球直连
    - https://dns.alidns.com/dns-query#🌎 全球直连&h3=true
  nameserver:
    - https://dns.google/dns-query#DNS解析&h3=true
    - https://cloudflare-dns.com/dns-query#DNS解析&h3=true
# —————————

global-ua: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36

proxies:
  - {name: 🌎 全球直连, type: direct, udp: true}
  - {name: ⛔️ 拒绝连接, type: reject}
  - {name: 🌐 DNS_Hijack, type: dns}

proxy_groups: &proxy_groups
    type: select
    proxies:
      - 总模式
      - ⛔️ 拒绝连接
      - 延迟最低
      - 故障转移
      - 负载均衡
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 其它地区
      - 🌎 全球直连
    <<: *A
# —————————
proxy-groups:
  - name: 总模式
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/All.svg"
    type: select
    proxies:
      - 延迟最低
      - 故障转移
      - 负载均衡
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 其它地区
      - 🌎 全球直连
# —————————

  - name: Telegram
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Telegram.svg"
    <<: *proxy_groups
    
  - name: Apple
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Apple.svg"
    <<: *proxy_groups
    
  - name: Microsoft
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Microsoft.svg"
    <<: *proxy_groups

  - name: OpenAI
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/OpenAI.svg"
    <<: *proxy_groups

  - name: Discord
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Discord.svg"
    <<: *proxy_groups

  - name: TikTok
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/TikTok.svg"
    <<: *proxy_groups

  - name: YouTube
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/YouTube.svg"
    <<: *proxy_groups

  - name: Netflix
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Netflix.svg"
    <<: *proxy_groups

  - name: Facebook
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Facebook.svg"
    <<: *proxy_groups

  - name: Google
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Google.svg"
    <<: *proxy_groups

  - name: GoogleFCM
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/GoogleFCM.svg"
    <<: *proxy_groups

  - name: GitHub
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/GitHub.svg"
    <<: *proxy_groups

  - name: Twitter(X)
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Twitter.svg"
    <<: *proxy_groups

  - name: DNS解析
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/DNS.svg"
    <<: *proxy_groups

  - name: 漏网之鱼
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/HBASE-copy.svg"
    <<: *proxy_groups

  - name: 广告拦截
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/No-ads-all.svg"
    type: select
    proxies:
      - ⛔️ 拒绝连接
      - 🌎 全球直连
      - REJECT-DROP
      - PASS #匹配规则

  - name: 延迟最低
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Return.svg"
    type: url-test
    <<: *A

  - name: 故障转移
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Return.svg"
    type: fallback
    <<: *A

  - name: 负载均衡
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Return.svg"
    type: load-balance
    strategy: round-robin
    <<: *A

  - name: 台湾节点
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/CN.svg"
    filter: "^(?=.*(台|新北|彰化|TW|Taiwan)).*$"
    <<: *All

  - name: 香港节点
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/HK.svg"
    filter: "^(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong)).*$"
    <<: *All

  - name: 日本节点
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/JP.svg"
    filter: "^(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)).*$"
    <<: *All

  - name: 美国节点
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/US.svg"
    filter: "^(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)).*$"
    <<: *All

  - name: 狮城节点
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Singapore.svg"
    filter: "^(?=.*(新加坡|坡|狮城|SG|Singapore)).*$"
    <<: *All

  - name: 其它地区
    icon: "https://raw.githubusercontent.com/MoGuangYu/Surfing/refs/heads/rm/Home/icon/Globe.svg"
    filter: "^(?!.*(港|HK|hk|Hong Kong|HongKong|hongkong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore|灾|网易|Netease|套餐|重置|剩余|到期|订阅|群|账户|流量|有效期|时间|官网)).*$"
    <<: *All
# —————————

rule-anchor:
  RuleDefault: &RuleDefault
    {type: http, behavior: classical, format: text, interval: 86400}
# —————————

rule-providers:
  CN_IP:
    <<: *RuleDefault
    path: ./rules/CN_IP.list
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/cn.list"

  private_Lan:
    <<: *RuleDefault
    path: ./rules/private_Lan.list
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/private.list"

  CN_域名:
    <<: *RuleDefault
    path: ./rules/CN_域名.list
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/cn.list"

  No-ads-all:
    <<: *RuleDefault
    path: ./rules/No-ads-all.list
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/category-ads-all.list"

  TikTok:
    <<: *RuleDefault
    path: ./rules/TikTok.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list"

  Facebook:
    <<: *RuleDefault
    path: ./rules/Facebook.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list"

  Telegram:
    <<: *RuleDefault
    path: ./rules/Telegram.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list"

  YouTube:
    <<: *RuleDefault
    path: ./rules/YouTube.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list"

  Google:
    <<: *RuleDefault
    path: ./rules/Google.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list"

  GoogleFCM:
    <<: *RuleDefault
    path: ./rules/GoogleFCM.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleFCM/GoogleFCM.list"

  Microsoft:
    <<: *RuleDefault
    path: ./rules/Microsoft.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list"

  Apple:
    <<: *RuleDefault
    path: ./rules/Apple.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list"

  OpenAI:
    <<: *RuleDefault
    path: ./rules/OpenAI.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list"

  Netflix:
    <<: *RuleDefault
    path: ./rules/Netflix.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.list"

  Discord:
    <<: *RuleDefault
    path: ./rules/Discord.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Discord/Discord.list"

  GitHub:
    <<: *RuleDefault
    path: ./rules/GitHub.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list"

  Twitter:
    <<: *RuleDefault
    path: ./rules/Twitter.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Twitter/Twitter.list"
    
  TW_IP:
     <<: *RuleDefault
     path: ./rules/TW_IP.list
     url: "https://raw.githubusercontent.com/savetti1987/openclash/refs/heads/main/TaiWan.list"
# —————————

rules:
  - DST-PORT,53,🌐 DNS_Hijack
  - RULE-SET,No-ads-all,广告拦截
  - RULE-SET,Twitter,Twitter(X)
  - RULE-SET,GitHub,GitHub
  - RULE-SET,TW_IP,台湾节点
  - RULE-SET,Discord,Discord
  - RULE-SET,TikTok,TikTok
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Facebook,Facebook
  - RULE-SET,OpenAI,OpenAI
  - RULE-SET,GoogleFCM,GoogleFCM
  - RULE-SET,Google,Google
  - RULE-SET,Apple,Apple
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Telegram,Telegram
  - RULE-SET,CN_域名,🌎 全球直连
  - RULE-SET,CN_IP,🌎 全球直连
  - RULE-SET,private_Lan,🌎 全球直连,no-resolve
  - MATCH,漏网之鱼
# —————————
